# Generated by Django 3.1.2 on 2021-01-24 10:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postUrl',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
