# Generated by Django 3.1.2 on 2021-01-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnblog', '0002_auto_20210124_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
