# Generated by Django 3.1.2 on 2021-01-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnblog', '0004_auto_20210125_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
