# Generated by Django 3.1.2 on 2021-01-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201124_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category',
            name='category_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
