# Generated by Django 3.1.2 on 2021-01-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productreview_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
