# Generated by Django 3.1.2 on 2021-01-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='body',
            field=models.CharField(max_length=512),
        ),
    ]
